[package]
name = "factory-planner"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
itertools = "0.14.0"
leptos = { version = "0.8.2", features = ["csr"] }
reactive_stores = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
